export const BLOG_ACTION_TYPE = {
  FORM_CHANGE: "FORM_CHANGE",
  SUBMIT_FORM: "SUBMIT_FORM",
  ADD_TO_BASKET: "ADD_TO_BASKET",
  REMOVE_FROM_BASKET: "REMOVE_FROM_BASKET",
  SUBMIT_REVIEW: "SUBMIT_REVIEW",
};
